{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: climateforcing
  version: {{ data.get('version') }}


source:
  git_url: ../

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - cftime>=1.4.0
    - numpy
    - netCDF4
    - pandas
    - scipy
    - tqdm

about:
  home: https://github.com/chrisroadmap/climateforcing
  license: Apache-2.0
  license_familY: Apache-2.0
  license_file: LICENSE
  summary: "An incomplete toolbox of scripts and modules used for analysis of climate models and climate data."

extra:
  recipe-maintainers:
    - chrisroadmap
