{% set version = GIT_DESCRIBE_TAG %}

package:
  name: climateforcing
  version: {{ version[1:] }}

source:
  git_url: ../

build:
  noarch: python

requirements:
  host:
    - python
    - setuptools
  build:
    - python  {{ python }}
  run:
    - python
    - cftime>=1.4.0
    - h5py
    - numpy
    - netCDF4
    - pandas
    - scipy
    - tqdm

about:
  home: https://github.com/chrisroadmap/climateforcing
  license: Apache-2.0
  license_file: LICENSE
  summary: "An incomplete toolbox of scripts and modules used for analysis of climate models and climate data."

extra:
  recipe-maintainers:
    - chrisroadmap
